services:
  database:
    image: mariadb
    restart: always
    ports:
     - 3306:3306
    volumes:
     - ./data:/var/lib/mysql
     - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: example